In [1]:
import enchant 
import pandas as pd

essays = pd.read_csv('../data/intermediate/prepped_essays_df.csv')

# ----------- ISOLATE JUST ESSAYS FROM 6th SET ------------ #
essays = essays[essays['essay_set'] == 6]
essays.dropna(axis=1, how='all', inplace=True)
essays.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score,prompt,has_source_material,source_text,grade_7,grade_8,grade_10
8886,14834,6,There were many obstacles that the builders fa...,2.0,2.0,2.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1
8887,14835,6,"Him from the start, there would have been many...",3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1
8888,14836,6,The builders of the Empire State Building face...,3.0,4.0,4.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1
8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1.0,1.0,1.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1
8890,14838,6,The builders of the Empire State Building face...,3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1

In [22]:
sample = essays.iloc[0, 2]
sample

"There were many obstacles that the builders faced in attempting to have dirigibles dock at the Empire State Building. Safety was an issue with the dirigibles because of the highly flammable gas hydrogen. So, if the dirigibles explode over New York many people could be killed in the very populated. Another problem is keeping the derigible @CAPS1 so people can get off while the wind moves the back end of itself. The only way was to tie lead weights down in the back of the dirigible, but it would be dangerous over people down below. So, these obstacles workers faced, never got past them and so they made the world's highest soda fountain and tea garden for tourists in the observation area."

In [25]:
d = enchant.Dict("en_US")
counter = []

for word in sample.split():  # Split the sentence into words and iterate through each.
#     if word[0].lower() > 'g':  # Check if the first character (lowercased) > g.
#         print(word.upper())  # If so, print the word all capitalised.
#     print(d.check(word))
    counter.append(d.check(word))
    
(counter.count(False), counter.count(True))

(6, 116)

In [30]:

# _individual_tups = []
_byRow = []

def getCorrectAndIncorrectSpelling(seriesOfEssays):
    """
    Returns a list of tuples:
    number of mispelled words, number of correctly spelled words 
    """
    _byRow = []

    for essay in seriesOfEssays:
        _individual = []
        for word in essay.split():

            _individual.append(d.check(word))

        _byRow.append((_individual.count(False), _individual.count(True)))

    return _byRow

In [36]:
spellings = getCorrectAndIncorrectSpelling(essays['essay'])

In [37]:
spellings

[(6, 116),
 (11, 169),
 (4, 162),
 (18, 175),
 (4, 158),
 (7, 161),
 (5, 143),
 (18, 110),
 (4, 110),
 (5, 125),
 (14, 219),
 (26, 286),
 (7, 206),
 (18, 177),
 (9, 126),
 (21, 131),
 (8, 133),
 (5, 121),
 (5, 82),
 (2, 86),
 (6, 108),
 (19, 225),
 (14, 163),
 (11, 222),
 (7, 109),
 (16, 151),
 (11, 199),
 (14, 184),
 (13, 146),
 (3, 106),
 (12, 157),
 (6, 169),
 (3, 60),
 (2, 100),
 (11, 193),
 (8, 138),
 (7, 123),
 (4, 130),
 (10, 134),
 (0, 111),
 (4, 108),
 (12, 89),
 (18, 180),
 (4, 96),
 (16, 119),
 (13, 116),
 (17, 141),
 (18, 176),
 (17, 207),
 (19, 203),
 (11, 138),
 (16, 170),
 (8, 156),
 (9, 170),
 (11, 163),
 (12, 157),
 (7, 160),
 (8, 123),
 (19, 181),
 (9, 75),
 (13, 173),
 (16, 145),
 (15, 245),
 (17, 160),
 (6, 185),
 (1, 103),
 (6, 130),
 (1, 31),
 (9, 203),
 (19, 144),
 (30, 167),
 (3, 71),
 (14, 98),
 (6, 110),
 (19, 127),
 (7, 135),
 (5, 81),
 (6, 59),
 (10, 94),
 (18, 134),
 (11, 166),
 (5, 106),
 (9, 153),
 (15, 149),
 (5, 163),
 (11, 109),
 (12, 165),
 (15, 162),
 (14, 186),
 (11, 157),
 (14, 144),
 (23, 121),
 (16, 230),
 (7, 73),
 (9, 173),
 (7, 95),
 (3, 151),
 (6, 79),
 (5, 172),
 (9, 161),
 (22, 193),
 (4, 105),
 (2, 115),
 (8, 132),
 (7, 170),
 (6, 49),
 (10, 177),
 (10, 233),
 (19, 189),
 (16, 188),
 (17, 187),
 (4, 71),
 (8, 136),
 (21, 194),
 (8, 129),
 (8, 55),
 (14, 193),
 (9, 125),
 (4, 63),
 (14, 172),
 (17, 99),
 (6, 112),
 (41, 273),
 (1, 37),
 (4, 61),
 (22, 136),
 (18, 152),
 (15, 126),
 (17, 155),
 (7, 170),
 (7, 125),
 (4, 87),
 (19, 136),
 (17, 205),
 (12, 157),
 (3, 82),
 (11, 144),
 (12, 167),
 (11, 190),
 (6, 100),
 (2, 113),
 (24, 106),
 (10, 144),
 (13, 136),
 (31, 200),
 (7, 50),
 (14, 117),
 (13, 131),
 (17, 133),
 (8, 79),
 (14, 107),
 (14, 162),
 (3, 138),
 (7, 192),
 (10, 189),
 (4, 125),
 (28, 170),
 (5, 172),
 (2, 93),
 (5, 102),
 (27, 240),
 (23, 230),
 (5, 119),
 (4, 73),
 (18, 146),
 (10, 174),
 (25, 239),
 (11, 164),
 (6, 123),
 (6, 113),
 (29, 239),
 (7, 112),
 (19, 156),
 (7, 169),
 (15, 178),
 (13, 224),
 (2, 28),
 (25, 190),
 (8, 130),
 (1, 53),
 (6, 106),
 (3, 121),
 (3, 42),
 (1, 5),
 (2, 88),
 (27, 221),
 (14, 79),
 (10, 166),
 (17, 170),
 (13, 113),
 (5, 118),
 (2, 76),
 (12, 176),
 (8, 133),
 (2, 87),
 (14, 181),
 (7, 167),
 (15, 207),
 (10, 158),
 (8, 178),
 (32, 222),
 (9, 142),
 (15, 148),
 (5, 117),
 (9, 125),
 (10, 132),
 (8, 149),
 (3, 95),
 (7, 220),
 (18, 118),
 (13, 147),
 (4, 112),
 (15, 199),
 (12, 174),
 (9, 128),
 (14, 161),
 (16, 171),
 (6, 144),
 (20, 164),
 (12, 200),
 (5, 78),
 (7, 111),
 (2, 105),
 (3, 56),
 (14, 165),
 (21, 123),
 (8, 171),
 (6, 117),
 (20, 175),
 (23, 219),
 (13, 119),
 (2, 117),
 (4, 130),
 (1, 75),
 (18, 225),
 (14, 227),
 (3, 131),
 (4, 124),
 (5, 107),
 (18, 196),
 (9, 214),
 (11, 76),
 (8, 166),
 (8, 105),
 (0, 66),
 (6, 144),
 (4, 109),
 (13, 157),
 (19, 144),
 (17, 208),
 (2, 102),
 (41, 229),
 (1, 61),
 (21, 109),
 (12, 140),
 (15, 200),
 (10, 128),
 (14, 121),
 (12, 155),
 (7, 142),
 (12, 210),
 (8, 65),
 (1, 47),
 (8, 231),
 (7, 110),
 (13, 154),
 (10, 126),
 (19, 157),
 (14, 168),
 (14, 173),
 (7, 113),
 (19, 184),
 (21, 161),
 (8, 132),
 (18, 145),
 (7, 139),
 (5, 113),
 (10, 136),
 (1, 78),
 (0, 19),
 (0, 75),
 (6, 134),
 (11, 110),
 (7, 87),
 (7, 101),
 (9, 108),
 (3, 100),
 (11, 158),
 (8, 127),
 (11, 148),
 (22, 143),
 (3, 148),
 (3, 28),
 (14, 211),
 (13, 135),
 (4, 95),
 (8, 134),
 (14, 105),
 (15, 139),
 (7, 136),
 (5, 55),
 (19, 113),
 (14, 140),
 (30, 222),
 (12, 189),
 (24, 192),
 (7, 48),
 (3, 18),
 (6, 173),
 (10, 79),
 (1, 151),
 (16, 169),
 (1, 107),
 (8, 144),
 (1, 120),
 (10, 73),
 (7, 136),
 (29, 275),
 (17, 157),
 (13, 153),
 (9, 160),
 (3, 180),
 (19, 105),
 (12, 244),
 (11, 180),
 (22, 208),
 (6, 141),
 (14, 173),
 (17, 161),
 (6, 105),
 (8, 158),
 (5, 103),
 (22, 191),
 (11, 179),
 (13, 215),
 (19, 251),
 (12, 117),
 (11, 136),
 (13, 185),
 (11, 191),
 (17, 160),
 (17, 178),
 (12, 224),
 (10, 156),
 (4, 95),
 (16, 181),
 (20, 202),
 (20, 192),
 (12, 205),
 (5, 100),
 (5, 149),
 (2, 79),
 (15, 174),
 (9, 124),
 (5, 66),
 (16, 184),
 (6, 191),
 (6, 157),
 (6, 144),
 (4, 50),
 (1, 80),
 (7, 84),
 (8, 126),
 (15, 134),
 (11, 150),
 (15, 156),
 (13, 160),
 (2, 75),
 (1, 97),
 (27, 257),
 (5, 97),
 (27, 141),
 (2, 88),
 (9, 91),
 (16, 156),
 (14, 134),
 (9, 113),
 (9, 172),
 (0, 75),
 (13, 112),
 (2, 106),
 (28, 185),
 (5, 101),
 (3, 62),
 (2, 93),
 (8, 128),
 (13, 162),
 (2, 87),
 (14, 213),
 (11, 176),
 (11, 111),
 (16, 194),
 (15, 164),
 (5, 160),
 (14, 212),
 (2, 95),
 (8, 142),
 (5, 163),
 (7, 152),
 (14, 182),
 (18, 207),
 (7, 107),
 (6, 132),
 (17, 109),
 (5, 31),
 (11, 175),
 (3, 62),
 (10, 161),
 (15, 201),
 (12, 158),
 (14, 136),
 (3, 53),
 (11, 176),
 (10, 130),
 (3, 182),
 (11, 228),
 (9, 163),
 (1, 128),
 (10, 118),
 (12, 136),
 (8, 55),
 (7, 95),
 (27, 213),
 (11, 132),
 (3, 55),
 (16, 194),
 (4, 89),
 (11, 133),
 (13, 138),
 (5, 130),
 (19, 139),
 (19, 213),
 (18, 101),
 (11, 207),
 (1, 39),
 (3, 66),
 (15, 108),
 (3, 85),
 (7, 116),
 (12, 216),
 (14, 119),
 (4, 125),
 (16, 213),
 (26, 169),
 (0, 71),
 (4, 131),
 (12, 139),
 (3, 141),
 (13, 172),
 (10, 122),
 (11, 167),
 (29, 208),
 (10, 102),
 (25, 111),
 (8, 54),
 (16, 141),
 (2, 91),
 (27, 180),
 (14, 62),
 (5, 120),
 (9, 128),
 (10, 152),
 (10, 196),
 (9, 81),
 (4, 111),
 (2, 89),
 (24, 213),
 (11, 164),
 (19, 171),
 (16, 161),
 (2, 119),
 (7, 153),
 (13, 170),
 (4, 130),
 (15, 255),
 (13, 121),
 (15, 175),
 (3, 114),
 (6, 158),
 (19, 142),
 (4, 124),
 (15, 206),
 (3, 126),
 (26, 121),
 (39, 282),
 (1, 36),
 (21, 203),
 (8, 233),
 (17, 170),
 (19, 143),
 (6, 100),
 (4, 107),
 (11, 187),
 (11, 201),
 (10, 129),
 (9, 161),
 (11, 202),
 (17, 200),
 (7, 128),
 (12, 180),
 (12, 191),
 (9, 144),
 (11, 137),
 (17, 168),
 (1, 85),
 (6, 108),
 (6, 129),
 (20, 154),
 (6, 148),
 (4, 50),
 (21, 179),
 (14, 143),
 (9, 127),
 (10, 131),
 (6, 170),
 (2, 145),
 (10, 85),
 (16, 167),
 (18, 113),
 (11, 186),
 (18, 190),
 (6, 121),
 (12, 138),
 (4, 135),
 (12, 153),
 (4, 127),
 (23, 169),
 (3, 129),
 (4, 76),
 (3, 56),
 (22, 109),
 (10, 152),
 (6, 126),
 (8, 152),
 (17, 152),
 (26, 138),
 (5, 128),
 (3, 38),
 (19, 194),
 (25, 215),
 (10, 131),
 (13, 138),
 (13, 172),
 (1, 82),
 (13, 108),
 (15, 172),
 (13, 120),
 (4, 109),
 (19, 221),
 (12, 164),
 (14, 159),
 (11, 174),
 (6, 10),
 (18, 114),
 (11, 126),
 (18, 238),
 (3, 56),
 (15, 162),
 (9, 132),
 (5, 127),
 (22, 182),
 (10, 115),
 (24, 190),
 (23, 170),
 (20, 182),
 (8, 132),
 (7, 131),
 (7, 96),
 (8, 105),
 (8, 110),
 (23, 166),
 (11, 76),
 (6, 76),
 (3, 110),
 (18, 260),
 (18, 153),
 (3, 80),
 (16, 177),
 (0, 110),
 (17, 93),
 (2, 61),
 (15, 170),
 (23, 237),
 (12, 188),
 (6, 154),
 (10, 216),
 (8, 147),
 (11, 133),
 (7, 122),
 (14, 146),
 (10, 85),
 (3, 125),
 (4, 50),
 (12, 143),
 (13, 147),
 (6, 119),
 (17, 239),
 (9, 106),
 (13, 219),
 (11, 167),
 (3, 81),
 (27, 181),
 (16, 227),
 (7, 174),
 (5, 174),
 (6, 82),
 (20, 140),
 (1, 66),
 (20, 185),
 (10, 142),
 (7, 134),
 (8, 84),
 (6, 189),
 (19, 192),
 (4, 218),
 (5, 102),
 (24, 262),
 (4, 133),
 (5, 114),
 (5, 155),
 (6, 155),
 (6, 124),
 (10, 129),
 (25, 258),
 (11, 114),
 (20, 176),
 (11, 146),
 (10, 169),
 (16, 236),
 (2, 96),
 (14, 184),
 (0, 257),
 (9, 222),
 (18, 238),
 (4, 70),
 (16, 154),
 (19, 178),
 (18, 173),
 (2, 79),
 (9, 174),
 (5, 223),
 (12, 141),
 (24, 163),
 (11, 177),
 (25, 163),
 (7, 118),
 (0, 67),
 (5, 156),
 (8, 67),
 (7, 84),
 (13, 217),
 (12, 97),
 (12, 158),
 (1, 39),
 (5, 119),
 (15, 135),
 (12, 72),
 (19, 140),
 (11, 134),
 (29, 136),
 (38, 198),
 (14, 241),
 (5, 100),
 (16, 150),
 (7, 162),
 (23, 178),
 (16, 100),
 (9, 115),
 (5, 144),
 (12, 158),
 (2, 27),
 (4, 86),
 (10, 219),
 (8, 200),
 (15, 287),
 (8, 226),
 (15, 174),
 (5, 165),
 (32, 181),
 (2, 94),
 (0, 82),
 (13, 160),
 (17, 168),
 (7, 118),
 (9, 208),
 (11, 179),
 (14, 164),
 (23, 166),
 (11, 182),
 (24, 200),
 (11, 127),
 (7, 125),
 (16, 183),
 (3, 124),
 (8, 143),
 (6, 107),
 (22, 279),
 (10, 89),
 (3, 53),
 (10, 195),
 (28, 147),
 (16, 219),
 (3, 71),
 (9, 99),
 (8, 128),
 (8, 147),
 (9, 100),
 (11, 112),
 (12, 171),
 (18, 135),
 (20, 154),
 (10, 148),
 (6, 190),
 (16, 187),
 (7, 116),
 (17, 236),
 (10, 140),
 (6, 100),
 (8, 108),
 (5, 91),
 (10, 161),
 (20, 148),
 (6, 139),
 (18, 180),
 (7, 156),
 (0, 98),
 (11, 200),
 (18, 277),
 (14, 161),
 (4, 95),
 (9, 137),
 (3, 160),
 (12, 173),
 (11, 88),
 (3, 137),
 (4, 59),
 (0, 79),
 (3, 45),
 (7, 185),
 (14, 161),
 (16, 238),
 (16, 176),
 (11, 162),
 (9, 144),
 (26, 208),
 (7, 84),
 (11, 93),
 (11, 90),
 (9, 179),
 (11, 171),
 (8, 269),
 (8, 72),
 (25, 158),
 (15, 135),
 (6, 97),
 (4, 110),
 (5, 153),
 (4, 88),
 (18, 163),
 (14, 133),
 (1, 111),
 (13, 155),
 (2, 127),
 (13, 190),
 (17, 134),
 (16, 150),
 (6, 102),
 (13, 173),
 (2, 131),
 (33, 131),
 (4, 72),
 (12, 134),
 (14, 182),
 (14, 179),
 (9, 125),
 (0, 104),
 (24, 209),
 (4, 193),
 (15, 158),
 (16, 182),
 (8, 219),
 (12, 177),
 (2, 127),
 (15, 230),
 (10, 171),
 (14, 122),
 (14, 149),
 (18, 186),
 (11, 197),
 (10, 117),
 (26, 229),
 (8, 87),
 (10, 139),
 (8, 85),
 (4, 111),
 (15, 169),
 (1, 89),
 (13, 172),
 (14, 72),
 (13, 122),
 (22, 154),
 (20, 171),
 (4, 130),
 (5, 131),
 (6, 63),
 (19, 113),
 (22, 148),
 (17, 210),
 (5, 170),
 (11, 151),
 (8, 136),
 (8, 145),
 (5, 155),
 (13, 120),
 (7, 118),
 (2, 42),
 (3, 120),
 (15, 125),
 (21, 250),
 (21, 158),
 (4, 160),
 (14, 211),
 (22, 166),
 (3, 100),
 (11, 202),
 (2, 126),
 (7, 147),
 (8, 51),
 (15, 146),
 (0, 12),
 (7, 212),
 (9, 230),
 (8, 76),
 (27, 223),
 (1, 104),
 (11, 119),
 (7, 109),
 (13, 110),
 (2, 67),
 (3, 96),
 (18, 168),
 (10, 134),
 (18, 191),
 (7, 162),
 (3, 84),
 (10, 133),
 (6, 141),
 (17, 196),
 (13, 189),
 (13, 107),
 (13, 128),
 (8, 115),
 (3, 130),
 (16, 69),
 (8, 161),
 (19, 203),
 (1, 129),
 (3, 45),
 (21, 179),
 (8, 124),
 (11, 116),
 (15, 153),
 (5, 101),
 (17, 119),
 (9, 115),
 (24, 237),
 (11, 203),
 (3, 87),
 (19, 165),
 (9, 166),
 (4, 79),
 (21, 219),
 (22, 183),
 (18, 183),
 (15, 195),
 (3, 175),
 (4, 98),
 (15, 141),
 (4, 132),
 (23, 199),
 (22, 184),
 (14, 160),
 (2, 101),
 (7, 111),
 (12, 177),
 (6, 148),
 (7, 70),
 (28, 144),
 (16, 199),
 (0, 98),
 (25, 120),
 (5, 80),
 (6, 140),
 (9, 113),
 (1, 39),
 (18, 161),
 (3, 108),
 (7, 170),
 (9, 125),
 (4, 40),
 (13, 121),
 (9, 99),
 (12, 177),
 (7, 129),
 (7, 73),
 (6, 173),
 (13, 104),
 (13, 96),
 (20, 161),
 (5, 125),
 (5, 136),
 (16, 183),
 (7, 170),
 (8, 178),
 (3, 102),
 (1, 37),
 (2, 49),
 (21, 175),
 (8, 182),
 (1, 36),
 (17, 191),
 (3, 53),
 (10, 117),
 (13, 110),
 (18, 143),
 (4, 106),
 (7, 131),
 (29, 219),
 (7, 111),
 (16, 158),
 (11, 140),
 (16, 175),
 (13, 137),
 (23, 246),
 (1, 83),
 (5, 92),
 (7, 160),
 (15, 164),
 (21, 161),
 (11, 190),
 (21, 172),
 (20, 148),
 (15, 208),
 (6, 115),
 (1, 74),
 (12, 110),
 (15, 240),
 (23, 217),
 (14, 152),
 (12, 170),
 (6, 137),
 (19, 146),
 (18, 161),
 (20, 205),
 (29, 207),
 (9, 153),
 (17, 168),
 (5, 111),
 (3, 115),
 (10, 85),
 (26, 184),
 (5, 135),
 (13, 166),
 (6, 51),
 (6, 102),
 (11, 107),
 (16, 175),
 (10, 116),
 (2, 120),
 (6, 147),
 (10, 165),
 (14, 148),
 (3, 143),
 (5, 68),
 (9, 121),
 (6, 119),
 (17, 121),
 (2, 81),
 (4, 127),
 (16, 142),
 (21, 152),
 (9, 127),
 (19, 147),
 (10, 143),
 (9, 90),
 (15, 142),
 (16, 112),
 (7, 192),
 (11, 155),
 (2, 28),
 (28, 367),
 (16, 129),
 (4, 149),
 (12, 226),
 (5, 131),
 (7, 122),
 (3, 145),
 (2, 33),
 (7, 76),
 (4, 85),
 ...]

In [34]:
list1, list2 = zip(*spellings)

In [35]:
list1

(6,
 11,
 4,
 18,
 4,
 7,
 5,
 18,
 4,
 5,
 14,
 26,
 7,
 18,
 9,
 21,
 8,
 5,
 5,
 2,
 6,
 19,
 14,
 11,
 7,
 16,
 11,
 14,
 13,
 3,
 12,
 6,
 3,
 2,
 11,
 8,
 7,
 4,
 10,
 0,
 4,
 12,
 18,
 4,
 16,
 13,
 17,
 18,
 17,
 19,
 11,
 16,
 8,
 9,
 11,
 12,
 7,
 8,
 19,
 9,
 13,
 16,
 15,
 17,
 6,
 1,
 6,
 1,
 9,
 19,
 30,
 3,
 14,
 6,
 19,
 7,
 5,
 6,
 10,
 18,
 11,
 5,
 9,
 15,
 5,
 11,
 12,
 15,
 14,
 11,
 14,
 23,
 16,
 7,
 9,
 7,
 3,
 6,
 5,
 9,
 22,
 4,
 2,
 8,
 7,
 6,
 10,
 10,
 19,
 16,
 17,
 4,
 8,
 21,
 8,
 8,
 14,
 9,
 4,
 14,
 17,
 6,
 41,
 1,
 4,
 22,
 18,
 15,
 17,
 7,
 7,
 4,
 19,
 17,
 12,
 3,
 11,
 12,
 11,
 6,
 2,
 24,
 10,
 13,
 31,
 7,
 14,
 13,
 17,
 8,
 14,
 14,
 3,
 7,
 10,
 4,
 28,
 5,
 2,
 5,
 27,
 23,
 5,
 4,
 18,
 10,
 25,
 11,
 6,
 6,
 29,
 7,
 19,
 7,
 15,
 13,
 2,
 25,
 8,
 1,
 6,
 3,
 3,
 1,
 2,
 27,
 14,
 10,
 17,
 13,
 5,
 2,
 12,
 8,
 2,
 14,
 7,
 15,
 10,
 8,
 32,
 9,
 15,
 5,
 9,
 10,
 8,
 3,
 7,
 18,
 13,
 4,
 15,
 12,
 9,
 14,
 16,
 6,
 20,
 12,
 5,
 7,
 2,
 3,
 14,
 21,
 8,
 6,
 20,
 23,
 13,
 2,
 4,
 1,
 18,
 14,
 3,
 4,
 5,
 18,
 9,
 11,
 8,
 8,
 0,
 6,
 4,
 13,
 19,
 17,
 2,
 41,
 1,
 21,
 12,
 15,
 10,
 14,
 12,
 7,
 12,
 8,
 1,
 8,
 7,
 13,
 10,
 19,
 14,
 14,
 7,
 19,
 21,
 8,
 18,
 7,
 5,
 10,
 1,
 0,
 0,
 6,
 11,
 7,
 7,
 9,
 3,
 11,
 8,
 11,
 22,
 3,
 3,
 14,
 13,
 4,
 8,
 14,
 15,
 7,
 5,
 19,
 14,
 30,
 12,
 24,
 7,
 3,
 6,
 10,
 1,
 16,
 1,
 8,
 1,
 10,
 7,
 29,
 17,
 13,
 9,
 3,
 19,
 12,
 11,
 22,
 6,
 14,
 17,
 6,
 8,
 5,
 22,
 11,
 13,
 19,
 12,
 11,
 13,
 11,
 17,
 17,
 12,
 10,
 4,
 16,
 20,
 20,
 12,
 5,
 5,
 2,
 15,
 9,
 5,
 16,
 6,
 6,
 6,
 4,
 1,
 7,
 8,
 15,
 11,
 15,
 13,
 2,
 1,
 27,
 5,
 27,
 2,
 9,
 16,
 14,
 9,
 9,
 0,
 13,
 2,
 28,
 5,
 3,
 2,
 8,
 13,
 2,
 14,
 11,
 11,
 16,
 15,
 5,
 14,
 2,
 8,
 5,
 7,
 14,
 18,
 7,
 6,
 17,
 5,
 11,
 3,
 10,
 15,
 12,
 14,
 3,
 11,
 10,
 3,
 11,
 9,
 1,
 10,
 12,
 8,
 7,
 27,
 11,
 3,
 16,
 4,
 11,
 13,
 5,
 19,
 19,
 18,
 11,
 1,
 3,
 15,
 3,
 7,
 12,
 14,
 4,
 16,
 26,
 0,
 4,
 12,
 3,
 13,
 10,
 11,
 29,
 10,
 25,
 8,
 16,
 2,
 27,
 14,
 5,
 9,
 10,
 10,
 9,
 4,
 2,
 24,
 11,
 19,
 16,
 2,
 7,
 13,
 4,
 15,
 13,
 15,
 3,
 6,
 19,
 4,
 15,
 3,
 26,
 39,
 1,
 21,
 8,
 17,
 19,
 6,
 4,
 11,
 11,
 10,
 9,
 11,
 17,
 7,
 12,
 12,
 9,
 11,
 17,
 1,
 6,
 6,
 20,
 6,
 4,
 21,
 14,
 9,
 10,
 6,
 2,
 10,
 16,
 18,
 11,
 18,
 6,
 12,
 4,
 12,
 4,
 23,
 3,
 4,
 3,
 22,
 10,
 6,
 8,
 17,
 26,
 5,
 3,
 19,
 25,
 10,
 13,
 13,
 1,
 13,
 15,
 13,
 4,
 19,
 12,
 14,
 11,
 6,
 18,
 11,
 18,
 3,
 15,
 9,
 5,
 22,
 10,
 24,
 23,
 20,
 8,
 7,
 7,
 8,
 8,
 23,
 11,
 6,
 3,
 18,
 18,
 3,
 16,
 0,
 17,
 2,
 15,
 23,
 12,
 6,
 10,
 8,
 11,
 7,
 14,
 10,
 3,
 4,
 12,
 13,
 6,
 17,
 9,
 13,
 11,
 3,
 27,
 16,
 7,
 5,
 6,
 20,
 1,
 20,
 10,
 7,
 8,
 6,
 19,
 4,
 5,
 24,
 4,
 5,
 5,
 6,
 6,
 10,
 25,
 11,
 20,
 11,
 10,
 16,
 2,
 14,
 0,
 9,
 18,
 4,
 16,
 19,
 18,
 2,
 9,
 5,
 12,
 24,
 11,
 25,
 7,
 0,
 5,
 8,
 7,
 13,
 12,
 12,
 1,
 5,
 15,
 12,
 19,
 11,
 29,
 38,
 14,
 5,
 16,
 7,
 23,
 16,
 9,
 5,
 12,
 2,
 4,
 10,
 8,
 15,
 8,
 15,
 5,
 32,
 2,
 0,
 13,
 17,
 7,
 9,
 11,
 14,
 23,
 11,
 24,
 11,
 7,
 16,
 3,
 8,
 6,
 22,
 10,
 3,
 10,
 28,
 16,
 3,
 9,
 8,
 8,
 9,
 11,
 12,
 18,
 20,
 10,
 6,
 16,
 7,
 17,
 10,
 6,
 8,
 5,
 10,
 20,
 6,
 18,
 7,
 0,
 11,
 18,
 14,
 4,
 9,
 3,
 12,
 11,
 3,
 4,
 0,
 3,
 7,
 14,
 16,
 16,
 11,
 9,
 26,
 7,
 11,
 11,
 9,
 11,
 8,
 8,
 25,
 15,
 6,
 4,
 5,
 4,
 18,
 14,
 1,
 13,
 2,
 13,
 17,
 16,
 6,
 13,
 2,
 33,
 4,
 12,
 14,
 14,
 9,
 0,
 24,
 4,
 15,
 16,
 8,
 12,
 2,
 15,
 10,
 14,
 14,
 18,
 11,
 10,
 26,
 8,
 10,
 8,
 4,
 15,
 1,
 13,
 14,
 13,
 22,
 20,
 4,
 5,
 6,
 19,
 22,
 17,
 5,
 11,
 8,
 8,
 5,
 13,
 7,
 2,
 3,
 15,
 21,
 21,
 4,
 14,
 22,
 3,
 11,
 2,
 7,
 8,
 15,
 0,
 7,
 9,
 8,
 27,
 1,
 11,
 7,
 13,
 2,
 3,
 18,
 10,
 18,
 7,
 3,
 10,
 6,
 17,
 13,
 13,
 13,
 8,
 3,
 16,
 8,
 19,
 1,
 3,
 21,
 8,
 11,
 15,
 5,
 17,
 9,
 24,
 11,
 3,
 19,
 9,
 4,
 21,
 22,
 18,
 15,
 3,
 4,
 15,
 4,
 23,
 22,
 14,
 2,
 7,
 12,
 6,
 7,
 28,
 16,
 0,
 25,
 5,
 6,
 9,
 1,
 18,
 3,
 7,
 9,
 4,
 13,
 9,
 12,
 7,
 7,
 6,
 13,
 13,
 20,
 5,
 5,
 16,
 7,
 8,
 3,
 1,
 2,
 21,
 8,
 1,
 17,
 3,
 10,
 13,
 18,
 4,
 7,
 29,
 7,
 16,
 11,
 16,
 13,
 23,
 1,
 5,
 7,
 15,
 21,
 11,
 21,
 20,
 15,
 6,
 1,
 12,
 15,
 23,
 14,
 12,
 6,
 19,
 18,
 20,
 29,
 9,
 17,
 5,
 3,
 10,
 26,
 5,
 13,
 6,
 6,
 11,
 16,
 10,
 2,
 6,
 10,
 14,
 3,
 5,
 9,
 6,
 17,
 2,
 4,
 16,
 21,
 9,
 19,
 10,
 9,
 15,
 16,
 7,
 11,
 2,
 28,
 16,
 4,
 12,
 5,
 7,
 3,
 2,
 7,
 4,
 ...)

In [38]:
# Using 'Address' as the column name and equating it to the list 
df2 = essays.assign(misspelt = list1) 
   
# Observe the result 
df2.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score,prompt,has_source_material,source_text,grade_7,grade_8,grade_10,misspelt
8886,14834,6,There were many obstacles that the builders fa...,2.0,2.0,2.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,6
8887,14835,6,"Him from the start, there would have been many...",3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,11
8888,14836,6,The builders of the Empire State Building face...,3.0,4.0,4.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,4
8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1.0,1.0,1.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,18
8890,14838,6,The builders of the Empire State Building face...,3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,4

In [39]:
essays = df2.assign(correct = list2)

In [40]:
essays.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score,prompt,has_source_material,source_text,grade_7,grade_8,grade_10,misspelt,correct
8886,14834,6,There were many obstacles that the builders fa...,2.0,2.0,2.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,6,116
8887,14835,6,"Him from the start, there would have been many...",3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,11,169
8888,14836,6,The builders of the Empire State Building face...,3.0,4.0,4.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,4,162
8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1.0,1.0,1.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,18,175
8890,14838,6,The builders of the Empire State Building face...,3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,4,158

In [41]:
from nltk import word_tokenize
tokens = word_tokenize(sample)

In [42]:
len(tokens)
# set(tokens)
# len(set(tokens))
# tokens.count('wub')
# tokens.count('the')
# 100 * tokens.count('wub') / float(len(tokens))
# 100 * tokens.count('the') / float(len(tokens))

134

In [43]:
sample

"There were many obstacles that the builders faced in attempting to have dirigibles dock at the Empire State Building. Safety was an issue with the dirigibles because of the highly flammable gas hydrogen. So, if the dirigibles explode over New York many people could be killed in the very populated. Another problem is keeping the derigible @CAPS1 so people can get off while the wind moves the back end of itself. The only way was to tie lead weights down in the back of the dirigible, but it would be dangerous over people down below. So, these obstacles workers faced, never got past them and so they made the world's highest soda fountain and tea garden for tourists in the observation area."

In [45]:
# using split() 
# to count words in string 
res = len(sample.split()) 
res

122

In [47]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+')
# text = "This is my text. It icludes commas, question marks? and other stuff. Also U.S.."
tokens = tokenizer.tokenize(sample)

In [48]:
# number of words in essay
len(tokens)

123

In [50]:
# unique words
len(set(tokens))

90

10.7.1. How to measure lexical diversity
One simple statistic for a text is to find the ratio of total words to unique words, or word tokens divided by word types. This is simple enough for you to calculate – with the caveat of insuring real number (float) division – as long as you filter out the punctuation. Oh, and you should round the resulting floating point numbers to two decimal places, otherwise Python returns it to fourteen decimal places:

In [52]:
# lexical diversity
lD = len(tokens) / float(len(set(tokens)))
round(lD, 2)

1.37

Now you might suspect that the lexical diversity of text could be proportional to how long the text is. The longer the text, the greater the chance for the author to use words that she has not used yet. You can test this hypothesis by plotting lexical diversity against the length of the texts. That, the length of the texts is the independent variable, on the X axis, against which you want to evaluate the lexical diversity of a text, the dependent variable on the Y axis. As the terminology suggests, the dependent variable depends on the independent one, which is shown quantitatively by plotting Y onto X.

In [54]:
import spacy
nlp = spacy.load('en_core_web_md')
parsed_essay = nlp(sample)

In [55]:
# number of sentences
for num, sentence in enumerate(parsed_essay.sents):
    print('Sentence {}:'.format(num + 1))
    print(sentence)
    print('')

Sentence 1:
There were many obstacles that the builders faced in attempting to have dirigibles dock at the Empire State Building.

Sentence 2:
Safety was an issue with the dirigibles because of the highly flammable gas hydrogen.

Sentence 3:
So, if the dirigibles explode over New York

Sentence 4:
many people could be killed in the very populated.

Sentence 5:
Another problem is keeping the derigible @CAPS1

Sentence 6:
so people can get off while the wind moves the back end of itself.

Sentence 7:
The only way was to tie lead weights down in the back of the dirigible, but it would be dangerous over people down below.

Sentence 8:
So, these obstacles workers faced, never got past them

Sentence 9:
and so they made the world's highest soda fountain and tea garden for tourists in the observation area.

In [56]:
for num, entity in enumerate(parsed_essay.ents):
    print('Entity {}:'.format(num + 1), entity, '-', entity.label_)
    print('')

Entity 1: the Empire State Building - FAC

Entity 2: New York - GPE

In [61]:
# number of parts of speech
token_pos = [token.pos_ for token in parsed_essay]

In [62]:
token_pos.count('ADV')

9

In [63]:
import urllib.request
from bs4 import BeautifulSoup

f = open('../data/intermediate/out.txt','w')

url = "https://satvocabulary.us/"
page = urllib.request.urlopen(url)

soup = BeautifulSoup(page)

In [64]:
soup.unicode

In [80]:
import re
regex = re.compile(".*?\((.*?)\)")
result = re.sub("[\(\[].*?[\)\]]", "", 'venal(ity)')

tab = soup.find("table",{"class":"WORDLIST"})
# tab
rows = tab.find_all('tr')
rows

top500SATWords = []

for row in rows:
    data = row.find_all("td")
    
    top500SATWords.append(re.sub("[\(\[].*?[\)\]]", "", ((data[1].get_text()).split(', ')[0])))

# top500SATWords

In [164]:
# token_lemma_punct = [(token.lemma_, token.is_punct for token in parsed_essay)]
# token_lemma_punct


# token_attributes = [(token.orth_,
#                      token.lemma,
#                      token.is_stop,
#                      token.is_punct for token in parsed_essay)]


token_attributes = [(token.orth_, token.is_stop, token.is_punct) for token in parsed_essay]

In [167]:
df = pd.DataFrame(token_attributes,
                  columns=['text',
                           'stop',
                           'punctuation'])

# s1 = pd.Series(['X0', 'X1', 'X2', 'X3'], name='X')

# In [19]: result = pd.concat([df1, s1], axis=1)

df3 = df[df['stop'] != True]

# df4 = df[df['punctuation'] != True]

# df.head()

# df4 df.

# print(len(df))

# print(len(df3))
df4 = df3[df3['punctuation'] == False]
len(df4)

52

In [168]:
low = df4['text'].tolist()

In [169]:
low  = [word.lower() for word in low]

In [170]:
low

['obstacles',
 'builders',
 'faced',
 'attempting',
 'dirigibles',
 'dock',
 'empire',
 'state',
 'building',
 'safety',
 'issue',
 'dirigibles',
 'highly',
 'flammable',
 'gas',
 'hydrogen',
 'dirigibles',
 'explode',
 'new',
 'york',
 'people',
 'killed',
 'populated',
 'problem',
 'keeping',
 'derigible',
 '@caps1',
 'people',
 'wind',
 'moves',
 'end',
 'way',
 'tie',
 'lead',
 'weights',
 'dirigible',
 'dangerous',
 'people',
 'obstacles',
 'workers',
 'faced',
 'got',
 'past',
 'world',
 'highest',
 'soda',
 'fountain',
 'tea',
 'garden',
 'tourists',
 'observation',
 'area']

In [171]:
low_joined = ' '.join(str(v) for v in low)

In [172]:
token_lemma = [token.lemma_ for token in nlp(low_joined)]

In [173]:
token_lemma

['obstacle',
 'builder',
 'face',
 'attempt',
 'dirigible',
 'dock',
 'empire',
 'state',
 'building',
 'safety',
 'issue',
 'dirigible',
 'highly',
 'flammable',
 'gas',
 'hydrogen',
 'dirigible',
 'explode',
 'new',
 'york',
 'people',
 'kill',
 'populated',
 'problem',
 'keep',
 'derigible',
 '@caps1',
 'people',
 'wind',
 'move',
 'end',
 'way',
 'tie',
 'lead',
 'weight',
 'dirigible',
 'dangerous',
 'people',
 'obstacles',
 'worker',
 'face',
 'get',
 'past',
 'world',
 'high',
 'soda',
 'fountain',
 'tea',
 'garden',
 'tourist',
 'observation',
 'area']

In [ ]:
top500SATWords.pop(0)
top500SATWords

In [135]:
top500_joined = ' '.join(str(v) for v in top500SATWords)

In [136]:
token_lemma_top500 = [token.lemma_ for token in nlp(top500_joined)]

In [ ]:
token_lemma_top500

In [138]:
print(len(token_lemma))
print(len(token_lemma_top500))

52
512

In [200]:
list1 = ['car', 'garden', 'cement', 'chicken']
list2 = ['automobile', 'nest', 'cementry', 'house']

c = sum(el in list1 for el in list2)
c

0

In [142]:
n_top500SAT = sum(el in token_lemma for el in token_lemma_top500)

In [143]:
n_top500SAT

0

In [260]:
sample
parsed_essay = nlp(sample)

# print(sorted(list(set(top500SATWords))))
# print(parsed_essay)

# print(set(parsed_essay))

def calculate_number_of_top500_SAT_words(parsed_essay, list_of_word_to_check_against):
    list_of_word_to_check_against = sorted(list(set(list_of_word_to_check_against)))
    token_attributes = [(token.lemma_, token.is_stop, token.is_punct) for token in parsed_essay]
    
    df = pd.DataFrame(token_attributes, columns=['text', 'stop', 'punctuation'])
    df2 = df[df['stop'] != True]
    df3 = df2[df2['punctuation'] != True]
    
    low = df3['text'].tolist()
    low  = [word.lower() for word in low]
    
    count = sum(el in low for el in list_of_word_to_check_against)
    return count

In [239]:
calculate_number_of_top500_SAT_words(set(parsed_essay), token_lemma_top500)

0

In [ ]:
# print(token_lemma_top500)

In [ ]:
# print(set(list1))
# print(bool(set(list1) & set(list2)))

In [197]:
# smth = set(list1) & set(list2)

In [ ]:
# smth

In [261]:
def buildDFSAT(df):
    n_top500 = []
    for essay in df['essay']:
        
        parsed_essay = nlp(essay)
        n_top500.append(calculate_number_of_top500_SAT_words(parsed_essay, token_lemma_top500))        
    
    essays = df.assign(n_top500 = n_top500) 
    return essays
        
essays = buildDFSAT(essays)

In [ ]:
essays

In [ ]:
# set(top500SATWords)

In [226]:
# sample2 = essays[essays['essay_id'] == 14856]

In [228]:
# sample2 = sample2['essay']

In [266]:
essays[essays['n_top500'] > 1]

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score,prompt,has_source_material,source_text,grade_7,grade_8,grade_10,misspelt,correct,n_top500
9053,15001,6,"Ambitious for its time, the idea of allowing d...",3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,11,164,2
9463,15411,6,In attempting to allow dirigibles to dock at t...,3.0,4.0,4.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,16,177,2
9779,15727,6,The @CAPS1 of the Empire State Building faced ...,1.0,2.0,2.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,9,113,2
9825,15773,6,"In the excerpt, The Mooring Mast by @ORGANIZAT...",2.0,2.0,2.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,11,190,2
9876,15824,6,The idea of using a mooring mast in order to a...,4.0,3.0,4.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,28,367,2
10034,15982,6,The Empire State Building was built as the tal...,3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,14,214,2
10349,16297,6,. The Empire State Building during it's constr...,3.0,3.0,3.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,15,169,2
10516,16464,6,The first obstacle that the can builders faced...,2.0,2.0,2.0,"Based on the excerpt, describe the obstacles t...",1,"When the Empire State Building was conceived, ...",0,0,1,14,155,2

In [269]:
sample2 = essays[essays['n_top500'] > 1].iloc[2, 2]
sample2

"The @CAPS1 of the Empire State Building faced many obstacles. By allowing the dirigibles to dock there, They had to build @CAPS2 planfronts on the side of the building, which means that they would be putting there life's in danger. They also had to deal with the electrical  problems within and without the building. The @CAPS1 on the outsides of the building would have to deal with the strong wind currents. They also have to make sure that the electrical system was working properly. If there were to be a stark of any sort of Fire, the hydrogen and helium were extremely flameable, and if a wire were too short, it could like the whole dirigible aflame and it would blow up."

In [270]:

calculate_number_of_top500_SAT_words(nlp(sample2), token_lemma_top500)

2

In [ ]:
# token_lemma_top500

In [ ]:
# token_attributes = [(token.lemma_, token.is_stop, token.is_punct) for token in nlp(sample2)]
    
# df = pd.DataFrame(token_attributes, columns=['text', 'stop', 'punctuation'])
# df2 = df[df['stop'] != True]
# df3 = df2[df2['punctuation'] != True]

# low = df3['text'].tolist()
# low  = [word.lower() for word in low]

# low

In [ ]:
# count = sum(el in low for el in token_lemma_top500)
# count

Fragments
The sentences you have encountered so far have been independent clauses. As you look more closely at your past writing assignments, you may notice that some of your sentences are not complete. A sentence that is missing a subject or a verb is called a fragment. A fragment may include a description or may express part of an idea, but it does not express a complete thought.

Fragment: Children helping in the kitchen.

Complete sentence: Children helping in the kitchen often make a mess.

You can easily fix a fragment by adding the missing subject or verb. In the example, the sentence was missing a verb. Adding often make a mess creates an S-V-N sentence structure.

Figure 1.1 Editing Fragments That Are Missing a Subject or a Verb



See whether you can identify what is missing in the following fragments.

Fragment: Told her about the broken vase.

Complete sentence: I told her about the broken vase.

Fragment: The store down on Main Street.

Complete sentence: The store down on Main Street sells music.